feat: spec overhaul + update workflow
Aliucord/plugins-repo-old pull request #2
Opened 2023-01-14 19:35 UTC by rushiiMachine

2023-01-14 20:42 UTC, TymanWasTaken requested changes
Whole bunch of things

2023-01-14 20:42 UTC, TymanWasTaken commented on .github/workflows/plugin-update.yml
> +          echo "dist_folder=$(jq -r '.distFolder' < .aliucordrc)" >> $GITHUB_OUTPUT
As mentioned on discord, this file should have correct naming
It is not an rc file, it is a json file and thus should have a name such as .alicuord.json

2023-01-14 20:42 UTC, TymanWasTaken commented on .github/workflows/plugin-update.yml
> +          jq -r '.buildAllCommand' < .aliucordrc | sh
I feel like the name "buildAllCommand" is kinda weird, why not just "buildCommand" or something

2023-01-14 20:42 UTC, TymanWasTaken commented on .github/workflows/plugin-update.yml
> +          name: INSECURE-DO-NOT-USE
An all caps artifact is kind of weird, just call it "Unverified-plugin" or something

2023-01-14 20:42 UTC, TymanWasTaken commented on .github/workflows/plugin-update.yml
> +          rm `jq -r '.ignoredPlugins | map("'\''\(.)'.zip\''") | join(" ")' < .aliucordrc`
Should probably add comments to say what the heck this jq code is doing

2023-01-14 20:42 UTC, TymanWasTaken commented on .github/workflows/plugin-update.yml
> +      - name: Update plugins in repo
I feel like this could be made a lot more readable if it was something besides just a long shell script, my initial plan was to use aliu cli to do all of the dirty work in managing the repo initially

2023-01-14 20:42 UTC, TymanWasTaken commented on .github/workflows/plugin-update.yml
> +      - name: Update plugins in repo
Or at the very least, extract all of this code into a file so its not just embedded into a yaml file (I like syntax highlighting)

2023-01-14 20:42 UTC, TymanWasTaken commented on .github/workflows/plugin-update.yml
> +      - name: Setup PNPM
I would rather this setup corepack instead, so it is not locked exclusively to pnpm (in b4 everything besides pnpm bad)
If you are going to have a config file for customization of build commands, might as well use corepack to make that even more loose

2023-01-14 20:42 UTC, TymanWasTaken commented on spec/modern/README.md
> +- `{plugin}/.owner`: A file of just the repository id as a string that currently owns this plugin. This is so that people cannot snipe ownership of plugins. If this is violated, the build will fail.
As explained on discord, this could be checked through metadata.json or the symlink folder

2023-01-14 20:42 UTC, TymanWasTaken commented on spec/modern/manifest.md
> +- `url` -> (NOT ALLOWED) Update url for 3rd party plugins
> it MUST have the required properties (with the correct type) listed below.

> - `authors` -> (optional)
> - `license` -> (optional)
> - `url` -> (NOT ALLOWED)

These two things conflict, they can't be required and also optional or forbidden

2023-01-14 20:42 UTC, TymanWasTaken commented on spec/modern/metadata.md
> -### fileName
Why is this removed

2023-01-14 20:42 UTC, TymanWasTaken commented on spec/modern/reviewing.md
> +**NOTE:** This process is for RN plugins only, as the Kt plugin store has not been made yet.
This is implicit, as it is literally in the spec/modern folder

2023-01-14 20:42 UTC, TymanWasTaken commented on spec/modern/manifest.md
> +- `version` -> A SemVer version
Should probably link to the semver page
```suggestion
- `version` -> A [SemVer](https://semver.org/) version
```

2023-01-14 20:42 UTC, TymanWasTaken commented on spec/modern/reviewing.md
> +  - Note that version bumps are not required! This indicates that the author is pushing out an unimportant change that does not need redownlading.
This explicitly breaks semver
> 3. Once a versioned package has been released, the contents of that version MUST NOT be modified. Any modifications MUST be released as a new version.

2023-01-14 20:42 UTC, TymanWasTaken commented on spec/modern/updater.md
> +    "plugin_name_here_name": {
I don't know why it was like this in the first place but "plugin name here name" makes no sense
```suggestion
    "plugin_name_here": {
```

2023-01-14 20:42 UTC, TymanWasTaken commented on spec/modern/updater.md
> +    "plugin_name_here_name": {
Also I feel like these placeholders should either have curly braces, be in all caps, or both to emphasize that they are placeholders

2023-01-14 20:42 UTC, TymanWasTaken commented on spec/modern/updater.md
> +### version (optional if no newName)
```suggestion
### version (optional, if no newName)
```

2023-01-14 20:42 UTC, TymanWasTaken commented on spec/modern/updater.md
> +### newName (optional if no version)
```suggestion
### newName (optional, if no version)
```

2023-01-14 20:46 UTC, TymanWasTaken commented
Oh I also forgot, we discussed signing earlier, is that still planned
If so, we should also add something in this specifying how exactly that works

2023-01-14 20:47 UTC, rushiiMachine commented on .github/workflows/plugin-update.yml
> +          name: INSECURE-DO-NOT-USE
people are very stupid

2023-01-14 20:51 UTC, rushiiMachine commented on .github/workflows/plugin-update.yml
> +      - name: Update plugins in repo
Ill add comments but extracting into a file isnt really viable
i would have to pull this repo twice

2023-01-14 20:57 UTC, TymanWasTaken commented on .github/workflows/plugin-update.yml
> +          branch_name="update/${{ github.event.inputs.repo_id }}"
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections

2023-01-14 21:00 UTC, TymanWasTaken commented on .github/workflows/plugin-update.yml
> +      - name: Update plugins in repo
How does that mean it isn't viable
Its one singular, short step, to make this so much more readable

2023-01-14 21:14 UTC, rushiiMachine commented on spec/modern/metadata.md
> -### fileName
plugins are moved into their respective folders by the zip name
they're also loaded in aliu by zip name
there's no reason why it should be different than the plugin name itself

2023-01-14 21:14 UTC, rushiiMachine commented on spec/modern/reviewing.md
> +**NOTE:** This process is for RN plugins only, as the Kt plugin store has not been made yet.
oh guh

2023-01-15 18:42 UTC, rushiiMachine commented on spec/modern/manifest.md
> +- `url` -> (NOT ALLOWED) Update url for 3rd party plugins
required != optional != not allowed
i was mentioning only the required properties

2023-01-18 20:13 UTC, TymanWasTaken approved these changes
Looks better, I still hate the fact that this relies on shell scripts but if this works, its fine for now

2023-01-18 21:04 UTC, merged